version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
      - db_data:/app/instance
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    command: poetry run gunicorn --bind 0.0.0.0:8000 app:app
    restart: always

volumes:
  db_data: