"""Add favorite field to users

Revision ID: 3b57ceb30fd3
Revises: 0a8a4a1eb509
Create Date: 2024-12-17 10:12:26.287615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b57ceb30fd3'
down_revision = '0a8a4a1eb509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ### 